/*
  Title:
    The Owls Are Not What They Seem

  Description:
    To pass the series of gates guarded by the owls, Kenneth needs to present them each with a highly realistic portrait of one.  Unfortunately, he is absolutely rubbish at drawing, and needs some code to return a brand new portrait with a moment's notice.
    All owl heads look like this:
    ''0v0''
    Such beautiful eyes!
    However, they differ in their plumage, which is always symmetrical, eg.:
       VVHVAV''0v0''VAVHVV
    or
    YYAYAH8XH''0v0''HX8HAYAYY
    So Kenneth needs a method that will take a garble of text generated by mashing at his keyboard (numbers and letters, but he knows how to avoid punctuation etc.) for a bit and give him a symmetrical owl with a lovely little face, with a truly symmetrical plumage made of uppercase letters and numbers.
    (To be clear, the acceptable characters for the plumage are 8,W,T,Y,U,I,O,A,H,X,V and M.)

  Kata Link:
    https://www.codewars.com/kata/the-owls-are-not-what-they-seem

  Discuss Link:
    https://www.codewars.com/kata/the-owls-are-not-what-they-seem/discuss

  Solutions Link:
    https://www.codewars.com/kata/the-owls-are-not-what-they-seem/solutions
*/

// Long Solution
/*
const owlPic = text => {
  const owlHead = `''0v0''`
  const owlPlumageLeft = (text.match(/[8WTYUIOAHXVM]/gi) || []).join('').toUpperCase()
  const owlPlumageRight = [...owlPlumageLeft].reverse().join('')

  return `${owlPlumageLeft}${owlHead}${owlPlumageRight}`
}
*/

// Short Solution
const owlPic = text =>
  [...text.toUpperCase()].reduceRight(
    (owl, char) => (/[8WTYUIOAHXVM]/.test(char) ? `${char}${owl}${char}` : owl),
    `''0v0''`
  )

// Function Export
module.exports = owlPic
